[2024-03-28T02:46:33.488+0000] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:46:33.495+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:46:33.498+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:33.498+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:46:33.588+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:33.584+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:46:33.596+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:46:33.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.249 seconds
[2024-03-28T02:47:38.108+0000] {processor.py:153} INFO - Started process (PID=658) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:47:38.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:47:38.125+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:38.123+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:47:38.163+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:38.159+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:47:38.168+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:47:38.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.213 seconds
[2024-03-28T02:48:28.010+0000] {processor.py:153} INFO - Started process (PID=886) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:48:28.015+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:48:28.021+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:28.018+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:48:28.046+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:28.042+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:48:28.053+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:48:28.124+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.126 seconds
[2024-03-28T02:48:58.497+0000] {processor.py:153} INFO - Started process (PID=1083) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:48:58.499+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:48:58.502+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:58.502+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:48:58.511+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:58.509+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:48:58.513+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:48:58.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.062 seconds
[2024-03-28T02:49:31.242+0000] {processor.py:153} INFO - Started process (PID=1295) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:49:31.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:49:31.248+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:31.247+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:49:31.264+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:31.258+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:49:31.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:49:31.306+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.070 seconds
[2024-03-28T02:50:03.134+0000] {processor.py:153} INFO - Started process (PID=1506) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:50:03.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:50:03.139+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:03.138+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:50:03.159+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:03.156+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:50:03.165+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:50:03.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.097 seconds
[2024-03-28T02:50:44.380+0000] {processor.py:153} INFO - Started process (PID=1712) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:50:44.384+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:50:44.387+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:44.387+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:50:44.409+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:44.404+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:50:44.411+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:50:44.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.117 seconds
[2024-03-28T02:51:15.498+0000] {processor.py:153} INFO - Started process (PID=1923) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:51:15.500+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:51:15.502+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:15.502+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:51:15.523+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:15.519+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:51:15.524+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:51:15.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.086 seconds
[2024-03-28T02:51:45.806+0000] {processor.py:153} INFO - Started process (PID=2117) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:51:45.808+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:51:45.810+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:45.809+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:51:45.832+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:45.830+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:51:45.834+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:51:45.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.086 seconds
[2024-03-28T02:52:21.423+0000] {processor.py:153} INFO - Started process (PID=2336) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:52:21.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:52:21.426+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:21.426+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:52:21.439+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:21.437+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:52:21.441+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:52:21.475+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.059 seconds
[2024-03-28T02:52:53.693+0000] {processor.py:153} INFO - Started process (PID=2561) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:52:53.696+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:52:53.698+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:53.698+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:52:53.714+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:53.709+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:52:53.716+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:52:53.756+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.068 seconds
[2024-03-28T02:53:24.638+0000] {processor.py:153} INFO - Started process (PID=2753) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:53:24.639+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:53:24.641+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:24.640+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:53:24.658+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:24.655+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:53:24.659+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:53:24.705+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.075 seconds
[2024-03-28T02:53:56.398+0000] {processor.py:153} INFO - Started process (PID=2971) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:53:56.401+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:53:56.404+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:56.403+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:53:56.420+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:56.417+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:53:56.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:53:56.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.070 seconds
[2024-03-28T02:54:27.809+0000] {processor.py:153} INFO - Started process (PID=3188) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:54:27.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:54:27.813+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:27.813+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:54:27.827+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:27.824+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:54:27.828+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:54:27.871+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.069 seconds
[2024-03-28T02:54:59.174+0000] {processor.py:153} INFO - Started process (PID=3404) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:54:59.176+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:54:59.177+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:59.177+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:54:59.191+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:59.189+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:54:59.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:54:59.227+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.059 seconds
[2024-03-28T02:55:30.762+0000] {processor.py:153} INFO - Started process (PID=3614) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:55:30.764+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:55:30.766+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:30.766+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:55:30.775+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:30.773+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:55:30.776+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:55:30.809+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.053 seconds
[2024-03-28T02:56:02.783+0000] {processor.py:153} INFO - Started process (PID=3831) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:56:02.785+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:56:02.786+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:02.786+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:56:02.795+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:02.793+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:56:02.798+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:56:02.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.055 seconds
[2024-03-28T02:56:33.852+0000] {processor.py:153} INFO - Started process (PID=4042) to work on /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:56:33.854+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/omnilog_poc_dag.py for tasks to queue
[2024-03-28T02:56:33.856+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:33.856+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:56:33.868+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:33.866+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/omnilog_poc_dag.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:56:33.870+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/omnilog_poc_dag.py
[2024-03-28T02:56:33.921+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/omnilog_poc_dag.py took 0.077 seconds
