[0m17:06:02.124891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11065dfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110b07150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110b07990>]}


============================== 17:06:02.135432 | ba947afd-613c-4c12-9eec-0057f45e426a ==============================
[0m17:06:02.135432 [info ] [MainThread]: Running with dbt=1.7.10
[0m17:06:02.136314 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/kwliao/Development/airflow_dbt/dags/dbt/', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug --profiles-dir /Users/kwliao/Development/airflow_dbt/dags/dbt/', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:06:02.137281 [info ] [MainThread]: dbt version: 1.7.10
[0m17:06:02.137884 [info ] [MainThread]: python version: 3.11.4
[0m17:06:02.138452 [info ] [MainThread]: python path: /Users/kwliao/Development/airflow_dbt/.airflow_dbt/bin/python3.11
[0m17:06:02.138988 [info ] [MainThread]: os info: macOS-14.3.1-x86_64-i386-64bit
[0m17:06:02.336527 [info ] [MainThread]: Using profiles dir at /Users/kwliao/Development/airflow_dbt/dags/dbt/
[0m17:06:02.337176 [info ] [MainThread]: Using profiles.yml file at /Users/kwliao/Development/airflow_dbt/dags/dbt/profiles.yml
[0m17:06:02.337679 [info ] [MainThread]: Using dbt_project.yml file at /Users/kwliao/Development/airflow_dbt/dbt_project.yml
[0m17:06:02.338288 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m17:06:02.341395 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.35201776, "process_user_time": 3.094079, "process_kernel_time": 0.617476, "process_mem_max_rss": "99373056", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:06:02.342398 [debug] [MainThread]: Command `dbt debug` failed at 17:06:02.342172 after 0.35 seconds
[0m17:06:02.343127 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110b2bd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110b2ba10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c56f4d0>]}
[0m17:06:02.344145 [debug] [MainThread]: Flushing usage events
[0m17:06:34.449747 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b7bdd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b81a250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b827a50>]}


============================== 17:06:34.456794 | eddab6d8-20e3-4bcd-bb08-53d166a805a9 ==============================
[0m17:06:34.456794 [info ] [MainThread]: Running with dbt=1.7.10
[0m17:06:34.457716 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/kwliao/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:06:34.458869 [info ] [MainThread]: dbt version: 1.7.10
[0m17:06:34.459620 [info ] [MainThread]: python version: 3.11.4
[0m17:06:34.460187 [info ] [MainThread]: python path: /Users/kwliao/Development/airflow_dbt/.airflow_dbt/bin/python3.11
[0m17:06:34.460868 [info ] [MainThread]: os info: macOS-14.3.1-x86_64-i386-64bit
[0m17:06:34.470703 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.hive'
[0m17:06:34.738840 [info ] [MainThread]: Using profiles dir at /Users/kwliao/.dbt
[0m17:06:34.739436 [info ] [MainThread]: Using profiles.yml file at /Users/kwliao/.dbt/profiles.yml
[0m17:06:34.739952 [info ] [MainThread]: Using dbt_project.yml file at /Users/kwliao/Development/airflow_dbt/dbt_project.yml
[0m17:06:34.740389 [info ] [MainThread]: Configuration:
[0m17:06:34.740863 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m17:06:34.741360 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m17:06:34.741856 [info ] [MainThread]: Required dependencies:
[0m17:06:34.742451 [debug] [MainThread]: Executing "git --help"
[0m17:06:34.794355 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:06:34.797137 [debug] [MainThread]: STDERR: "b''"
[0m17:06:34.797866 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:06:34.798561 [info ] [MainThread]: Connection test skipped since no profile was found
[0m17:06:34.799304 [info ] [MainThread]: [31m2 checks failed:[0m
[0m17:06:34.799902 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "default", target "dev" invalid: Runtime Error
    Could not find adapter type hive!

Runtime Error
  Credentials in profile "mp_metrics_hourly", target "dev" invalid: Runtime Error
    thrift connection method requires additional dependencies. 
    Install the additional required dependencies with `pip install dbt-spark[PyHive]`

Runtime Error
  Credentials in profile "mp_revamp", target "dev" invalid: Runtime Error
    thrift connection method requires additional dependencies. 
    Install the additional required dependencies with `pip install dbt-spark[PyHive]`


[0m17:06:34.800484 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/kwliao/Development/airflow_dbt/dbt_project.yml> not found

[0m17:06:34.803632 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.46081212, "process_user_time": 2.951416, "process_kernel_time": 0.518093, "process_mem_max_rss": "100868096", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:06:34.804645 [debug] [MainThread]: Command `dbt debug` failed at 17:06:34.804415 after 0.46 seconds
[0m17:06:34.805402 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b827410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b81ab10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072c7590>]}
[0m17:06:34.806117 [debug] [MainThread]: Flushing usage events
