[2024-03-28T02:45:44.205+0000] {processor.py:153} INFO - Started process (PID=253) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:45:44.211+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:45:44.216+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:45:44.213+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:45:46.161+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:45:46.146+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:45:46.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:45:46.371+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 2.182 seconds
[2024-03-28T02:46:53.890+0000] {processor.py:153} INFO - Started process (PID=482) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:46:53.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:46:53.913+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:53.908+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:46:56.384+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:56.380+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:46:56.386+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:46:56.418+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 2.548 seconds
[2024-03-28T02:47:46.398+0000] {processor.py:153} INFO - Started process (PID=711) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:47:46.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:47:46.403+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:46.402+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:47:49.988+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:49.983+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:47:49.991+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:47:50.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 3.639 seconds
[2024-03-28T02:48:34.191+0000] {processor.py:153} INFO - Started process (PID=931) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:48:34.193+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:48:34.194+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:34.193+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:48:36.503+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:36.494+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:48:36.505+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:48:36.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 2.343 seconds
[2024-03-28T02:49:07.120+0000] {processor.py:153} INFO - Started process (PID=1141) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:49:07.122+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:49:07.123+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:07.123+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:49:08.033+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:08.023+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:49:08.035+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:49:08.053+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.937 seconds
[2024-03-28T02:49:38.117+0000] {processor.py:153} INFO - Started process (PID=1334) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:49:38.146+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:49:38.148+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:38.148+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:49:39.402+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:39.393+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:49:39.405+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:49:39.436+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 1.327 seconds
[2024-03-28T02:50:09.769+0000] {processor.py:153} INFO - Started process (PID=1545) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:50:09.770+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:50:09.771+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:09.771+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:50:11.298+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:11.290+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:50:11.300+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:50:11.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 1.575 seconds
[2024-03-28T02:50:47.855+0000] {processor.py:153} INFO - Started process (PID=1741) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:50:47.857+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:50:47.859+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:47.858+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:50:49.094+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:49.087+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:50:49.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:50:49.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 1.325 seconds
[2024-03-28T02:51:19.342+0000] {processor.py:153} INFO - Started process (PID=1951) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:51:19.346+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:51:19.348+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:19.348+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:51:20.684+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:20.679+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:51:20.686+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:51:20.705+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 1.370 seconds
[2024-03-28T02:51:51.344+0000] {processor.py:153} INFO - Started process (PID=2168) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:51:51.348+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:51:51.350+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:51.350+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:51:52.976+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:52.969+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:51:52.983+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:51:53.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 1.688 seconds
[2024-03-28T02:52:23.561+0000] {processor.py:153} INFO - Started process (PID=2379) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:52:23.566+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:52:23.569+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:23.569+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:52:25.702+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:25.691+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:52:25.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:52:25.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 2.198 seconds
[2024-03-28T02:52:56.884+0000] {processor.py:153} INFO - Started process (PID=2600) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:52:56.886+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:52:56.888+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:56.887+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:52:57.676+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:57.673+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:52:57.679+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:52:57.691+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.818 seconds
[2024-03-28T02:53:28.221+0000] {processor.py:153} INFO - Started process (PID=2797) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:53:28.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:53:28.224+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:28.224+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:53:29.117+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:29.114+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:53:29.119+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:53:29.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.921 seconds
[2024-03-28T02:54:00.621+0000] {processor.py:153} INFO - Started process (PID=3020) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:54:00.625+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:54:00.632+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:00.628+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:54:01.587+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:01.585+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:54:01.588+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:54:01.601+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.998 seconds
[2024-03-28T02:54:31.876+0000] {processor.py:153} INFO - Started process (PID=3226) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:54:31.877+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:54:31.879+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:31.879+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:54:32.622+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:32.620+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:54:32.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:54:32.636+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.764 seconds
[2024-03-28T02:55:03.038+0000] {processor.py:153} INFO - Started process (PID=3437) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:55:03.039+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:55:03.040+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:03.040+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:55:04.089+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:04.085+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:55:04.090+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:55:04.106+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 1.074 seconds
[2024-03-28T02:55:34.600+0000] {processor.py:153} INFO - Started process (PID=3647) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:55:34.602+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:55:34.604+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:34.603+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:55:35.323+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:35.321+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:55:35.324+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:55:35.336+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.742 seconds
[2024-03-28T02:56:05.865+0000] {processor.py:153} INFO - Started process (PID=3858) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:56:05.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:56:05.868+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:05.868+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:56:06.814+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:06.810+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:56:06.816+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:56:06.846+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.987 seconds
[2024-03-28T02:56:36.973+0000] {processor.py:153} INFO - Started process (PID=4069) to work on /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:56:36.974+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py for tasks to queue
[2024-03-28T02:56:36.975+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:36.975+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:56:37.872+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:37.869+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py", line 29, in <module>
    my_sf_pass = Variable.get("sf_pass_houzz_pro")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sf_pass_houzz_pro does not exist'
[2024-03-28T02:56:37.873+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py
[2024-03-28T02:56:37.918+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_pro_companies.py took 0.950 seconds
